### ISSUE TITLE
path option not working

### ISSUE THREAD

**Issue by KCFindstr** [erclu/check-crlf#8]
I provided a path option and hoping only to check files matching the path, but found that all CRLF line endings were outputed.

BTW, does this action support glob patterns for file name matching?

**Comment by erclu** [comment]
I probably found out the reason; the find expression in the script didn't really use the path you provided. I think i fixed it so i'll close the issue but please let me know if it's working as expected by answering here.

To answer your second point: no it does not. I could probably do it and also implement the stuff we were talking about in #3  but honestly i'd feel like i was re-implementing functionality that is already "kind of" present in git itself (see [disclaimer here](https://github.com/erclu/check-crlf/blob/94acb86c2a41b0a46bd8087b63a06f0457dd0c6c/README.md#disclaimer))

if your use case is to have some files with lf and some with crlf based on a glob pattern i'd probably commit to the repository root a `.gitattributes` file similar to this:

```
# Set the default behavior: everything normalized to LF
* text eol=lf

# Declare files that will always have CRLF line endings on checkout.
<YOUR_GLOB_HERE> text eol=crlf
```

**Comment by KCFindstr** [comment]
Thank you! I confirm v1.2.0 handles the path option correctly.
